# ~/.config/starship.toml

add_newline = false

[username]
style_user = "bold cyan"
format = "[$user]($style) âˆˆ "
show_always = true

[hostname]
format = "[$hostname]($style):"
style = "bold dimmed white"

[directory]
format = "[$path](italic green)[$lock_symbol]($lock_style) "

[character]
success_symbol = "[â¯](bold yellow)[â¯](bold cyan)[â¯](bold purple)"
error_symbol = "[â¯](bold bright-red)[â¯](bold red)[â¯](bold yellow)"
vimcmd_symbol = "[â®](bold yellow)[â®](bold cyan)[â®](bold purple)"

[battery]
full_symbol = "ğŸ”‹ "
empty_symbol = "ğŸ’€ "
charging_symbol = "âš¡ "
discharging_symbol = "ğŸª« "

[git_branch]
format = "[$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

#[git_state]
#format = "[\($state( $progress_current of $progress_total)\)]($style) "

[git_status]
style = "bright white"
format = "$all_status$head_behind"

[package]
disabled = true

[line_break]
disabled = true

[cmd_duration]
disabled = true

[aws]
disabled = true

[julia]
format = "[$symbol$verion](style)"
style = "bold green"

[golang]
format = "[ğŸ¹$version]($style)"

[python]
format = "[ğŸ$version]($style)"
style = "bold green"

[rust]
format = "[ğŸ¦€$version]($style)"

[nodejs]
format = "[ğŸ¤–$version]($style)"
